
method: predcorr # or nufi (not implemented in Python yet)
physics:
  charge: -1.0
  mass: 1.0
  knudsen: 1.0
interp:
  order: 3
grid:
  nx: 128 # 2^7
  nv: 128
  lx: 31.41592653589793   # 2*pi/k with k = 0.2
  lv: 15.707963267948966  # 2*pi
inicond:
  case: landau_damping
  k: 0.5
  alpha: 0.05
time:
  nt_max: 4000
  dt: 1
  tend: 15
  plot_freq: 10
optim:
  target: two_stream
  eps: 0.05
  v0: 3
  k: 0.2
  filter_xv: ones
  filter_t: ones
  lr: 1
  Nopt: 20
io:
  save_dir: null
  compression_method: POD
  dt_save: 5.0
  restart:
    enabled: false
    file: null
