# Converted from matlab/params/PARAMS_two_stream.m
method: predcorr
physics:
  charge: -1.0
  mass: 1.0
  knudsen: 1
interp:
  order: 3
grid:
  nx: 256  # 2^10
  nv: 256
  lx: 12.566370614359172   # 2*pi/k with k = 0.5
  lv: 6.283185307179586  # 2*pi
inicond:
  case: two_stream
  alpha: null
  eps: 0.05
  v0: 3
  k: 0.5
time:
  nt_max: 4000
  dt: 0.1
  tend: 1
  plot_freq: 10
optim:
  case: landau_damping
  k: 0.5
  alpha: 0.01
  filter_xv: ones
  filter_t: ones
  lr: 0.5
  Nopt: 15